export class Openings {
	static openings = [
		[
			//white
			{ moves: 'e4 c5 Nf3 d6 d4', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 e6 d4', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 Nc6 d4', name: `Sicilian` },
			{ moves: 'e4 c5 Nc3 Nc6 Bb5', name: `Closed Sicilian` },
			{ moves: 'e4 c5 c3 Nf6 e5', name: `Alapin Sicilian` },
			{ moves: 'e4 c5 c3 d5 exd5', name: `Alapin Sicilian` },
			{ moves: 'e4 e5 Nf3 Nc6 Bb5', name: `Ruy López` },
			{ moves: 'e4 e5 Nf3 Nc6 Bc4', name: `Italian` },
			{ moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5 b4', name: `Italian, Evan's Gambit` },
			{ moves: 'e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7 Kxf7 Qf3+', name: `Italian, Fried Liver` },
			{ moves: 'e4 e5 Nf3 Nc6 d4', name: `Scotch` },
			{ moves: 'e4 e5 Nf3 Nc6 Nc3', name: `Three Knights` },
			{ moves: 'e4 e5 Nf3 Nf6 Nxe5', name: `Petrov` },
			{ moves: 'e4 e5 Nf3 d6 d4', name: `Philidor` },
			{ moves: 'e4 e5 Bc4 Nf6 d3', name: `Bishop` },
			{ moves: 'e4 e5 Nc3 Nf6 g3', name: `Vienna` },
			{ moves: 'e4 e5 f4 exf4 Nf3', name: `King's Gambit` },
			{ moves: 'd4 Nf6 c4 e6 Nf3', name: `Indian` },
			{ moves: 'd4 Nf6 c4 g6 Nc3', name: `Indian` },
			{ moves: 'd4 Nf6 c4 e6 g3', name: `Catalan` },
			{ moves: 'd4 Nf6 Nf3 e6 c4', name: `Indian` },
			{ moves: 'd4 Nf6 Nf3 g6 c4', name: `Indian` },
			{ moves: 'd4 Nf6 Bg5 Ne4 Bf4', name: `Trompowsky` },
			{ moves: 'd4 d5 c4 dxc4 Nf3', name: `Queen's Gambit Accepted` },
			{ moves: 'd4 d5 c4 c6 Nf3', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 c4 e6 Nf3', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 Nf3 Nf6 c4', name: `London` },
			{ moves: 'd4 d5 Nf3 Nf6 Bf4', name: `London` },
			{ moves: 'd4 d5 Nf3 c6 c4', name: `London` },
			{ moves: 'd4 d5 Bf4 Nf6 e3', name: `London` },
			{ moves: 'Nf3 Nf6 c4 e6 g3', name: `English` },
			{ moves: 'Nf3 Nf6 c4 e6 Nc3', name: `English` },
			{ moves: 'Nf3 d5 g3 Nf6 Bg2', name: `English` },
			{ moves: 'Nf3 d5 g3 c6 Bg2', name: `English` },
			{ moves: 'Nf3 d5 g3 g6 Bg2', name: `English` },
			{ moves: 'Nf3 d5 d4 Nf6 c4', name: `Queen's Pawn` },
			{ moves: 'Nf3 d5 c4 c6 e3', name: `Réti` },
			{ moves: 'Nf3 d5 c4 e6 g3', name: `Agincourt` },
			{ moves: 'Nf3 d5 e4 dxe4 Ng5 Nf6 d3 exd3 Bxd3 h6 Nxf7 Kxf7 Bg6+ Kxg6 Qxd8', name: `ICBM Gambit` },
			{ moves: 'Nf3 d5 e4 dxe4 Ng5 Nf6 d3 exd3 Bxd3 h6 Nxf7 Kxf7 Bg6+ Kg8 Qxd8', name: `ICBM Gambit` },
			{ moves: 'c4 Nf6 Nc3 e5 Nf3', name: `English` },
			{ moves: 'c4 e5 Nc3 Nf6 Nf3', name: `English` },
			{ moves: 'c4 e6 Nc3 d5 d4', name: `English` },
			{ moves: 'c4 e6 Nf3 d5 g3', name: `English` },
		],
		[
			//black
			{ moves: 'e4 c5 Nf3 d6 d4 cxd4', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 d6 Bb5+ Nd7', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 e6 d4 cxd4', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 Nc6 d4 cxd4', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 Nc6 Bb5 g6', name: `Sicilian` },
			{ moves: 'e4 c5 Nf3 Nc6 Nc3 g6', name: `Sicilian` },
			{ moves: 'e4 e5 Nf3 Nc6 Bb5 a6', name: `King's Pawn Game` },
			{ moves: 'e4 e5 Nf3 Nc6 Bc4 Bc5', name: `King's Pawn Game` },
			{ moves: 'e4 e5 Nf3 Nc6 Bb5 Nf6', name: `Berlin` },
			{ moves: 'e4 e5 Nf3 Nf6 Nxe5 d6', name: `King's Pawn Game` },
			{ moves: 'e4 e5 Nf3 Nf6 Nxe5 Nc6 Nxc6 dxc6 d3 Bc5 Be2 h5 O-O Ng4 h3 Qd6', name: `Stafford Gambit` },
			{ moves: 'e4 e5 Nc3 Nf6 g3 d5', name: `Vienna` },
			{ moves: 'e4 e5 Bc4 Nf6 d3 Nc6', name: `Bishop Berlin Defence` },
			{ moves: 'e4 e6 d4 d5 Nc3 Bb4', name: `French` },
			{ moves: 'e4 e6 d4 d5 Nd2 c5', name: `French` },
			{ moves: 'e4 c6 d4 d5 e5 Bf5', name: `Caro-Kann` },
			{ moves: 'e4 c6 d4 d5 Nc3 dxe4', name: `Caro-Kann` },
			{ moves: 'e4 c6 d4 d5 exd5 cxd5', name: `Caro-Kann` },
			{ moves: 'e4 c6 d4 d5 Nd2 dxe4', name: `Caro-Kann` },
			{ moves: 'e4 d6 d4 Nf6 Nc3 g6', name: `Pirc` },
			{ moves: 'e4 g6 d4 Bg7 Nc3 d6', name: `Modern` },
			{ moves: 'e4 g6 d4 Bg7 Nf3 d6', name: `Modern` },
			{ moves: 'e4 d5 exd5 Qxd5 Nc3 Qa5', name: `Scandinavian` },
			{ moves: 'e4 Nf6 e5 Nd5 d4 d6', name: `Alekhine` },
			{ moves: 'd4 Nf6 c4 e6 Nf3 b6', name: `Queen's Pawn` },
			{ moves: 'd4 Nf6 c4 e6 Nf3 d5', name: `Queen's Pawn` },
			{ moves: 'd4 Nf6 c4 e6 Nf3 Bb4+', name: `Queen's Pawn` },
			{ moves: 'd4 Nf6 c4 e6 Nf3 c5', name: `Queen's Pawn` },
			{ moves: 'd4 Nf6 c4 g6 Nc3 Bg7', name: `King's Indian Defence` },
			{ moves: 'd4 Nf6 c4 g6 Nc3 d5', name: `Grünfeld` },
			{ moves: 'd4 Nf6 c4 c5 d5 b5', name: `Benko Gambit` },
			{ moves: 'd4 Nf6 Nf3 e6 c4 b6', name: `Queen's Indian Defence` },
			{ moves: 'd4 Nf6 Nf3 g6 c4 Bg7', name: `King's Indian` },
			{ moves: 'd4 Nf6 Nf3 g6 g3 Bg7', name: `King's Indian` },
			{ moves: 'd4 d5 c4 c6 Nf3 Nf6', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 c4 c6 Nc3 Nf6', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 c4 e6 Nf3 Nf6', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 c4 e6 Nc3 Nf6', name: `Queen's Gambit Declined` },
			{ moves: 'd4 d5 Nf3 Nf6 c4 e6', name: `Queen's Pawn` },
			{ moves: 'Nf3 Nf6 c4 e6 g3 d5', name: `English Neo-Catalan` },
			{ moves: 'Nf3 Nf6 c4 g6 Nc3 Bg7', name: `English` },
			{ moves: 'Nf3 Nf6 g3 g6 Bg2 Bg7', name: `Réti, King's Indian Attack` },
			{ moves: 'Nf3 Nf6 g3 d5 Bg2 c6', name: `Réti` },
			{ moves: 'Nf3 Nf6 g3 b6 Bg2 Bb7', name: `Réti` },
			{ moves: 'Nf3 Nf6 d4 e6 c4 b6', name: `Queen's Indian Defence` },
			{ moves: 'Nf3 Nf6 d4 e6 c4 d5', name: `Queen's Pawn` },
			{ moves: 'Nf3 Nf6 d4 e6 g3 b5', name: `Queen's Pawn` },
			{ moves: 'Nf3 Nf6 d4 e6 e3 b6', name: `Queen's Pawn` },
			{ moves: 'Nf3 Nf6 d4 g6 c4 Bg7', name: `King's Indian` },
			{ moves: 'Nf3 Nf6 d4 g6 g3 Bg7', name: `King's Indian` },
			{ moves: 'Nf3 Nf6 d4 g6 Bg5 Bg7', name: `King's Indian` },
			{ moves: 'Nf3 d5 g3 Nf6 Bg2 c6', name: `Réti, King's Indian Attack` },
			{ moves: 'Nf3 d5 g3 c6 Bg2 Bg4', name: `Réti, King's Indian Attack` },
			{ moves: 'Nf3 d5 d4 Nf6 c4 e6', name: `Queen's Pawn` },
			{ moves: 'Nf3 d5 c4 d4 b4 f6', name: `Réti, Advance Variation` },
			{ moves: 'c4 Nf6 Nc3 e5 Nf3 Nc6', name: `English, Four Knights` },
			{ moves: 'c4 Nf6 Nf3 e6 g3 d5', name: `English, Neo-Catalan` },
			{ moves: 'c4 Nf6 Nf3 g6 Nc3 Bg7', name: `English` },
			{ moves: 'c4 Nf6 g3 c6 Bg2 d5', name: `English` },
			{ moves: 'c4 Nf6 g3 c6 Nf3 d5', name: `English` },
			{ moves: 'c4 e5 Nc3 Nf6 Nf3 Nc6', name: `English, Four Knights` },
			{ moves: 'c4 e5 Nc3 Nf6 g3 Bb4', name: `English` },
			{ moves: 'c4 e5 Nc3 Nc6 Nf3 Nf6', name: `English, Four Knights` },
			{ moves: 'c4 e5 Nc3 Nc6 g3 g6', name: `English` },
			{ moves: 'c4 e5 Nc3 Bb4 Nd5 Be7', name: `English` },
			{ moves: 'c4 e5 Nc3 Bb4 g3 Nf6', name: `English` },
			{ moves: 'c4 e5 g3 Nf6 Bg2 c6', name: `English` },
			{ moves: 'c4 e5 g3 Nc6 Bg2 g6', name: `English` },
		],
	];
}
